apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-challenge
  template:
    metadata:
      labels:
        app: go-challenge
    spec:
      containers:
        - name: go-challenge-container
          image: theeido/gochallenge
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080